# Generated by Django 5.2.7 on 2025-10-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_created_at_category_name_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
