# Generated by Django 5.2.7 on 2025-10-18 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_productimage_position'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subcategory',
            new_name='Genre',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='subcategory',
            new_name='genre',
        ),
    ]
