# Generated by Django 5.2.7 on 2025-10-19 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_product_condition_productcondition'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('gift', 'Подарочное'), ('excellent', 'Отличное'), ('good', 'Хорошее'), ('fair', 'Удовлетворительное')], default='excellent', max_length=16),
        ),
        migrations.DeleteModel(
            name='ProductCondition',
        ),
    ]
