# Generated by Django 5.2.7 on 2025-10-19 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_product_condition_delete_productcondition'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='collection',
            field=models.CharField(blank=True, choices=[('new', 'Новинки'), ('sale', 'Акции'), ('recommend', 'Рекомендуем')], max_length=16, null=True),
        ),
    ]
