# Generated by Django 5.2.7 on 2026-02-25 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_slug_lengths'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': 'Баннер', 'verbose_name_plural': 'Баннеры'},
        ),
        migrations.AlterModelOptions(
            name='bookpurchasephoto',
            options={'verbose_name': 'Фото заявки на выкуп', 'verbose_name_plural': 'Фото заявок на выкуп'},
        ),
        migrations.AlterModelOptions(
            name='bookpurchaserequest',
            options={'ordering': ('-created_at',), 'verbose_name': 'Заявка на выкуп', 'verbose_name_plural': 'Заявки на выкуп'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='deepseekprompt',
            options={'verbose_name': 'Промпт DeepSeek', 'verbose_name_plural': 'Промпты DeepSeek'},
        ),
        migrations.AlterModelOptions(
            name='erpproductsyncstate',
            options={'verbose_name': 'Состояние синхронизации ERP', 'verbose_name_plural': 'Состояния синхронизации ERP'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ('position', 'name'), 'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='productreview',
            options={'ordering': ('-created_at',), 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
    ]
