# Generated by Django 5.2.7 on 2026-02-25 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoriteitem',
            options={'ordering': ('-added_at',), 'verbose_name': 'Элемент избранного', 'verbose_name_plural': 'Элементы избранного'},
        ),
        migrations.AlterModelOptions(
            name='favoritelist',
            options={'ordering': ('-updated_at',), 'verbose_name': 'Список избранного', 'verbose_name_plural': 'Списки избранного'},
        ),
    ]
